baseURL = 'https://berghetti.github.io/'
languageCode = 'pt-br'
title = 'Mayco Blog'
author = 'Mayco S. Berghetti'
theme = 'dark-theme-editor'

enableGitInfo = true

# Customized info shown in header of the page
[params.header]
  title = "Blog"

# syntax highlight
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 2

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'
